Airlines/Airlines.WebUI/Controllers/NavigatorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Airlines.Data.Entities;
using Airlines.Data.Repository;

namespace Airlines.WebUI.Controllers
{
    [Authorize(Roles = "admin")]
    public class NavigatorsController : Controller
    {
        

        IAirlineRepository<Navigator> repository;
        public NavigatorsController()
        {

        }
        public NavigatorsController(IAirlineRepository<Navigator> repo)
        {
            repository = repo;
        }

        // GET: Navigators
        public ActionResult Index()
        {
            return View(repository.GetList());
        }

        // GET: Navigators/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Navigators/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,FirstName,LastName")] Navigator navigator)
        {
            if (ModelState.IsValid)
            {
                repository.Create(navigator);
                repository.Save();
                return RedirectToAction("Index", "Admin", "");
            }

            return View(navigator);
        }

        // GET: Navigators/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Navigator navigator = repository.GetByID(id);
            if (navigator == null)
            {
                return HttpNotFound();
            }
            return View(navigator);
        }

        // POST: Navigators/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,FirstName,LastName")] Navigator navigator)
        {
            if (ModelState.IsValid)
            {
                repository.Update(navigator);
                repository.Save();
                return RedirectToAction("Index", "Admin", "");
            }
            return View(navigator);
        }

        // GET: Navigators/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Navigator navigator = repository.GetByID(id);
            if (navigator == null)
            {
                return HttpNotFound();
            }
            return View(navigator);
        }

        // POST: Navigators/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
           
            repository.Delete(id);
            repository.Save();
            return RedirectToAction("Index", "Admin", "");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                repository.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Airlines/Airlines.WebUI/Controllers/PilotsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Airlines.Data.Entities;
using Airlines.Data.Repository;
using Airlines.WebUI.Models;

namespace Airlines.WebUI.Controllers
{
    [Authorize(Roles = "admin")]
    public class PilotsController : Controller
    {
        IAirlineRepository<Pilot> repository;
        public PilotsController()
        {

        }
        public PilotsController(IAirlineRepository<Pilot> repo)
        {
            repository = repo;
        }
        public ActionResult Index()
        {
            AdminViewModel adminWiewModel = new AdminViewModel
            {
                Pilots = repository.GetList()
            };
            return PartialView(adminWiewModel);
        }

        // GET: Pilots/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pilot pilot = repository.GetByID(id);
            if (pilot == null)
            {
                return HttpNotFound();
            }
            return View(pilot);
        }

        // GET: Pilots/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Pilots/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,FirstName,LastName")] Pilot pilot)
        {
            if (ModelState.IsValid)
            {
                repository.Create(pilot);
                repository.Save();
                return RedirectToAction("Index","Admin","");
            }

            return View(pilot);
        }

        // GET: Pilots/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pilot pilot = repository.GetByID(id);
            if (pilot == null)
            {
                return HttpNotFound();
            }
            return View(pilot);
        }

        // POST: Pilots/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,FirstName,LastName")] Pilot pilot)
        {
            if (ModelState.IsValid)
            {
                repository.Update(pilot);
                repository.Save();
                return RedirectToAction("Index", "Admin", "");
            }
            return View(pilot);
        }

        // GET: Pilots/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pilot pilot = repository.GetByID(id);
            if (pilot == null)
            {
                return HttpNotFound();
            }
            return View(pilot);
        }

        // POST: Pilots/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            repository.Delete(id);
            repository.Save();
            return RedirectToAction("Index", "Admin", "");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                repository.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Airlines/Airlines.WebUI/Controllers/RaceTeamsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Airlines.WebUI.Models;
using Airlines.Data.Entities;
using Airlines.Data.Repository;
using Airlines.Data.OtherActions;
using static Airlines.Data.OtherActions.Methods;

namespace Airlines.WebUI.Controllers
{
    public class RaceTeamsController : Controller
    {
        IAirlineRepository<RaceTeam> repository;
        public RaceTeamsController()
        {

        }
        public RaceTeamsController(IAirlineRepository<RaceTeam> repo)
        {
            repository = repo;
        }
        
        [Authorize(Roles = "admin, dispatcher")]
        public ActionResult Show(int id)
        {
            AdminViewModel adminViewModel = new AdminViewModel
            {
                RaceTeam = repository.GetByID(id)
            };
            return PartialView(adminViewModel);
        }
        [Authorize(Roles = "admin, dispatcher")]
        public ActionResult ShowAll()
        {
            return View(repository.GetList());
        }
        // GET: RaceTeams/Create
        [Authorize(Roles = "admin, dispatcher")]
        public ActionResult Create(int id)
        {
            ViewBag.PilotID = new SelectList(GetCustomPilots(), "ID", "Name" , "");
            ViewBag.NavigatorID = new SelectList(GetCustomNavigators(), "ID","Name", "");
            ViewBag.Stuardess1 = new SelectList(GetCustomStuardesses(), "ID", "Name", "");
            ViewBag.Stuardess2 = new SelectList(GetCustomStuardesses(), "ID", "Name", "2");
            ViewBag.RadioManID = new SelectList(GetCustomRadiomen(), "ID", "Name", "");
            return View();
        }
        [Authorize(Roles = "admin, dispatcher")]
        // POST: RaceTeams/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int id, RaceTeam raceTeam, FormCollection form)
        {
            if (ModelState.IsValid)
            {
                repository.Create(raceTeam);
                repository.Save();
                int? firstStuardess = 0;
                int? secondStuardess = 0;

                if (!string.IsNullOrEmpty(form["Stuardess1"]))
                {
                    firstStuardess = int.Parse(form["Stuardess1"]);
                }
                if (!string.IsNullOrEmpty(form["Stuardess2"]))
                {
                    secondStuardess = int.Parse(form["Stuardess2"]);
                }
                UpdateStuardesses(firstStuardess, secondStuardess, raceTeam.ID);
                UpdateRace(id, raceTeam.ID);
            }
            return RedirectToAction("Index","Dispatcher","");
        }
        [Authorize(Roles = "admin, dispatcher")]
        // GET: RaceTeams/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RaceTeam raceTeam = repository.GetByID(id);
            if (raceTeam == null)
            {
                return HttpNotFound();
            }
            return View(raceTeam);
        }

        [Authorize(Roles="dispatcher, admin")]
        // POST: RaceTeams/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(RaceTeam raceTeam, FormCollection form)
        {
            if (ModelState.IsValid)
            {
                repository.Update(raceTeam);
                repository.Save();
                int? firstStuardess = 0;
                int? secondStuardess = 0;

                if (!string.IsNullOrEmpty(form["Stuardess1"]))
                {
                    firstStuardess = int.Parse(form["Stuardess1"]);
                }
                if (!string.IsNullOrEmpty(form["Stuardess2"]))
                {
                    secondStuardess = int.Parse(form["Stuardess2"]);
                }
                
                UpdateStuardesses(firstStuardess,secondStuardess,raceTeam.ID);
             
                return RedirectToAction("ShowAll");
            }
            return View(raceTeam);
        }
        [Authorize(Roles = "admin, dispatcher")]
        // GET: RaceTeams/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RaceTeam raceTeam = repository.GetByID(id);
            if (raceTeam == null)
            {
                return HttpNotFound();
            }
            return View(raceTeam);
        }
        [Authorize(Roles = "admin, dispatcher")]
        // POST: RaceTeams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            repository.Delete(id);
            repository.Save();
            return RedirectToAction("ShowAll");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                repository.Dispose();
            }
            base.Dispose(disposing);
    }
    }
}

Airlines/Airlines.WebUI/Controllers/RadioMenController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Airlines.Data.Entities;
using Airlines.Data.Repository;

namespace Airlines.WebUI.Controllers
{
    [Authorize(Roles = "admin")]
    public class RadioMenController : Controller
    {
        IAirlineRepository<RadioMan> repository;
        public RadioMenController()
        {

        }
        public RadioMenController(IAirlineRepository<RadioMan> repo)
        {
            repository = repo;
        }
        // GET: RadioMen
        public ActionResult Index()
        {
            return View(repository.GetList());
        }

        // GET: RadioMen/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RadioMen/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,FirstName,LastName")] RadioMan radioMan)
        {
            if (ModelState.IsValid)
            {
                repository.Create(radioMan);
                repository.Save();
                return RedirectToAction("Index", "Admin", "");
            }

            return View(radioMan);
        }

        // GET: RadioMen/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RadioMan radioMan = repository.GetByID(id);
            if (radioMan == null)
            {
                return HttpNotFound();
            }
            return View(radioMan);
        }

        // POST: RadioMen/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,FirstName,LastName")] RadioMan radioMan)
        {
            if (ModelState.IsValid)
            {
                repository.Update(radioMan);
                repository.Save();
                return RedirectToAction("Index", "Admin", "");
            }
            return View(radioMan);
        }

        // GET: RadioMen/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RadioMan radioMan = repository.GetByID(id);
            if (radioMan == null)
            {
                return HttpNotFound();
            }
            return View(radioMan);
        }

        // POST: RadioMen/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            repository.Delete(id);
            repository.Save();
            return RedirectToAction("Index", "Admin", "");
        }
        


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                repository.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Airlines/Airlines.WebUI/Views/Admin/Index.cshtml
@model Airlines.WebUI.Models.AdminViewModel
@{
    ViewBag.Title = "Admin panel";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<div id="modDialog" class="modal fade">
    <div id="dialogContent" class="modal-dialog"></div>
</div>
<div class="container-tab">
    <ul class="accordion-tabs">
        <li class="tab-head-cont">
            <a href="#" class="is-active">Stuardesses</a>
            <section>
                <p>@{Html.RenderPartial("Stuardesses", Model);}</p>
            </section>
        </li>
        <li class="tab-head-cont">
            <a href="#">Races</a>
            <section>
                <p>
                <p>@{Html.RenderPartial("Races", Model);}</p>
                </p>
            </section>
        </li>
        <li class="tab-head-cont">
            <a href="#">Navigators</a>
            <section>
                <p>
                <p>@{Html.RenderPartial("Navigators", Model);}</p>
                </p>
            </section>
        </li>
        <li class="tab-head-cont">
            <a href="#">RadioMen</a>
            <section>
                <p>
                <p>@{Html.RenderPartial("RadioMen", Model);}</p>
                </p>
            </section>
        </li>
        <li class="tab-head-cont">
            <a href="#">Pilots</a>
            <section>
                <p>
                <p>@Html.Action("Index", "Pilots", "")</p>
                </p>
            </section>
        </li>
        <li class="tab-head-cont">
            <a href="#">Queries</a>
            <section>
                <p>
                <p>@{Html.RenderPartial("Queries", Model);}</p>
                </p>
            </section>
        </li>
    </ul>

</div>
    @section Scripts {
        <script src="~/Scripts/ModalWindow.js"></script>
        <script src="~/Scripts/TabPages.js"></script>
    }

Airlines/Airlines.WebUI/Views/Admin/Navigators.cshtml
@model Airlines.WebUI.Models.AdminViewModel
    <div class="table-wrap">
        <p class="text-center">
            @Html.ActionLink("Add a new navigator", "Create", "Navigators", "", "")
        </p>
        <table class="table">
            <tr>
                <th>
                    First Name
                </th>
                <th>
                    Last Name
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model.Navigators)
            {
                <tr>
                    <td class="align-middle">
                        @Html.DisplayFor(modelItem => item.FirstName)
                    </td>
                    <td class="align-middle">
                        @Html.DisplayFor(modelItem => item.LastName)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", "Navigators", new { id = item.ID }, "") |
                        @Html.ActionLink("Delete", "Delete", "Navigators", new { id = item.ID }, "")
                    </td>
                </tr>
            }

        </table>
    </div>

Airlines/Airlines.WebUI/Views/Admin/Queries.cshtml
@model Airlines.WebUI.Models.AdminViewModel

    <div class="table-wrap">
        <table class="table">
            <tr>
                <th>
                    Status
                </th>
                <th>
                    Query
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model.Queries)
            {
                <tr>
                    @if (item.IsAccepted == null)
                    {
                        <td class="align-middle">Pending</td>

                        <td class="align-middle">
                            The query to apply team
                            @if (item.RaceTeam != null)
                            {
                                @Html.ActionLink(item.RaceTeamID.ToString(), "Show", "RaceTeams", new { id = item.RaceTeam.ID }, new { @class = "compItem" })
                            }
                            else
                            {
                                @item.RaceTeamID
                            }
                            to @item.Race.Name race (@item.Race.Date)
                        </td>
                        <td>
                            @Html.ActionLink("Accept", "Update", "Queries", new { id = item.ID }, new { @class = "text-success" }) <span> </span>
                            @Html.ActionLink("Decline", "Delete", "Queries", new { id = item.ID }, new { @class = "text-danger" })
                        </td>
                    }

                </tr>
            }

        </table>
        </div>

Airlines/Airlines.WebUI/Views/Admin/Races.cshtml
@model Airlines.WebUI.Models.AdminViewModel
<div class="table-wrap">
    <p class="text-center">
        @Html.ActionLink("Add a new race", "Create", "Races", "", "")
    </p>
    <table class="table">
        <tr>
            <th>
                Race Team
            </th>
            <th>
                Name
            </th>
            <th>
                Departure
            </th>
            <th>
                Destinaton
            </th>
            <th>
                Date
            </th>
            <th>
                Race Status
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model.Races)
        {
            <tr>
                <td class="align-middle">
                    @Html.DisplayFor(modelItem => item.RaceTeam.ID) <br/>
                    @if (item.RaceTeam != null)
                    {
                        @Html.ActionLink("Check roster", "Show", "RaceTeams", new { id = item.RaceTeam.ID }, new { @class = "compItem" })
                    }
                </td>
                <td class="align-middle">
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td class="align-middle">
                    @Html.DisplayFor(modelItem => item.Departure)
                </td>
                <td class="align-middle">
                    @Html.DisplayFor(modelItem => item.Destinaton)
                </td>
                <td class="align-middle">
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                @if (item.IsDeparted == true)
                {
                    <td class="align-middle">
                        In flight
                    </td>
                }
                else
                {
                    <td class="align-middle">
                        Incoming race
                    </td>
                }
                <td>
                    @Html.ActionLink("Edit", "Edit", "Races", new { id = item.ID }, "") |
                    @Html.ActionLink("Delete", "Delete", "Races", new { id = item.ID }, "")
                </td>
            </tr>
        }

    </table>
</div>

Airlines/Airlines.WebUI/Views/Admin/RadioMen.cshtml
@model Airlines.WebUI.Models.AdminViewModel
    <div class="table-wrap">
        <p class="text-center">
            @Html.ActionLink("Add a new radioman", "Create", "RadioMen", "", "")
        </p>
        <table class="table">
            <tr>
                <th>
                    First Name
                </th>
                <th>
                    Last Name
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model.RadioMen)
            {
                <tr>
                    <td class="align-middle">
                        @Html.DisplayFor(modelItem => item.FirstName)
                    </td>
                    <td class="align-middle">
                        @Html.DisplayFor(modelItem => item.LastName)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", "RadioMen", new { id = item.ID }, "")|
                        @Html.ActionLink("Delete", "Delete", "RadioMen", new { id = item.ID }, "")
                    </td>
                </tr>
            }

        </table>
        </div>

Airlines/Airlines.WebUI/Views/Admin/Stuardesses.cshtml
@model Airlines.WebUI.Models.AdminViewModel

    <div class="table-wrap">
        <p class="text-center">
            @Html.ActionLink("Add a new stuardess", "Create", "Stuardesses", "", "")
        </p>
        <table class="table">
            <tr>
                <th>
                    Team
                </th>
                <th>
                    Form
                </th>
                <th>
                    First Name
                </th>
                <th>
                    Last Name
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model.Stuardesses)
            {
                <tr>
                    <td class="align-middle">
                        @Html.DisplayFor(modelItem => item.Team.ID)
                    </td>
                    <td class="align-middle">
                        @Html.DisplayFor(modelItem => item.Form)
                    </td>
                    <td class="align-middle">
                        @Html.DisplayFor(modelItem => item.FirstName)
                    </td>
                    <td class="align-middle">
                        @Html.DisplayFor(modelItem => item.LastName)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", "Stuardesses", new { id = item.ID }, "")|
                        @Html.ActionLink("Delete", "Delete", "Stuardesses", new { id = item.ID }, "")
                    </td>
                </tr>
            }

        </table>
        </div>