Airlines/Airlines.WebUI/Controllers/DispatcherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Airlines.Data.Repository;
using System.Data.Entity;
using Airlines.Data.Entities;
using Airlines.WebUI.Models;

namespace Airlines.WebUI.Controllers
{
    [Authorize(Roles = "dispatcher")]
    public class DispatcherController : Controller
    {
        UnitOfWork unitOfWork;

        public DispatcherController()
        {
            unitOfWork = new UnitOfWork();
        }

        // GET: Dispatcher
        public ActionResult Index()
        {
            AdminViewModel a = new AdminViewModel
            {
                Races = unitOfWork.Races.GetList()
            };
            return View(a);
        }
        public ActionResult Queries()
        {
            return View(unitOfWork.Queries.GetList());
        }
    }
}

Airlines/Airlines.WebUI/Controllers/RaceTeamsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Airlines.WebUI.Models;
using Airlines.Data.Entities;
using Airlines.Data.Repository;
using Airlines.Data.OtherActions;
using static Airlines.Data.OtherActions.Methods;

namespace Airlines.WebUI.Controllers
{
    public class RaceTeamsController : Controller
    {
        IAirlineRepository<RaceTeam> repository;
        public RaceTeamsController()
        {

        }
        public RaceTeamsController(IAirlineRepository<RaceTeam> repo)
        {
            repository = repo;
        }
        
        [Authorize(Roles = "admin, dispatcher")]
        public ActionResult Show(int id)
        {
            AdminViewModel adminViewModel = new AdminViewModel
            {
                RaceTeam = repository.GetByID(id)
            };
            return PartialView(adminViewModel);
        }
        [Authorize(Roles = "admin, dispatcher")]
        public ActionResult ShowAll()
        {
            return View(repository.GetList());
        }
        // GET: RaceTeams/Create
        [Authorize(Roles = "admin, dispatcher")]
        public ActionResult Create(int id)
        {
            ViewBag.PilotID = new SelectList(GetCustomPilots(), "ID", "Name" , "");
            ViewBag.NavigatorID = new SelectList(GetCustomNavigators(), "ID","Name", "");
            ViewBag.Stuardess1 = new SelectList(GetCustomStuardesses(), "ID", "Name", "");
            ViewBag.Stuardess2 = new SelectList(GetCustomStuardesses(), "ID", "Name", "2");
            ViewBag.RadioManID = new SelectList(GetCustomRadiomen(), "ID", "Name", "");
            return View();
        }
        [Authorize(Roles = "admin, dispatcher")]
        // POST: RaceTeams/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int id, RaceTeam raceTeam, FormCollection form)
        {
            if (ModelState.IsValid)
            {
                repository.Create(raceTeam);
                repository.Save();
                int? firstStuardess = 0;
                int? secondStuardess = 0;

                if (!string.IsNullOrEmpty(form["Stuardess1"]))
                {
                    firstStuardess = int.Parse(form["Stuardess1"]);
                }
                if (!string.IsNullOrEmpty(form["Stuardess2"]))
                {
                    secondStuardess = int.Parse(form["Stuardess2"]);
                }
                UpdateStuardesses(firstStuardess, secondStuardess, raceTeam.ID);
                UpdateRace(id, raceTeam.ID);
            }
            return RedirectToAction("Index","Dispatcher","");
        }
        [Authorize(Roles = "admin, dispatcher")]
        // GET: RaceTeams/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RaceTeam raceTeam = repository.GetByID(id);
            if (raceTeam == null)
            {
                return HttpNotFound();
            }
            return View(raceTeam);
        }

        [Authorize(Roles="dispatcher, admin")]
        // POST: RaceTeams/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(RaceTeam raceTeam, FormCollection form)
        {
            if (ModelState.IsValid)
            {
                repository.Update(raceTeam);
                repository.Save();
                int? firstStuardess = 0;
                int? secondStuardess = 0;

                if (!string.IsNullOrEmpty(form["Stuardess1"]))
                {
                    firstStuardess = int.Parse(form["Stuardess1"]);
                }
                if (!string.IsNullOrEmpty(form["Stuardess2"]))
                {
                    secondStuardess = int.Parse(form["Stuardess2"]);
                }
                
                UpdateStuardesses(firstStuardess,secondStuardess,raceTeam.ID);
             
                return RedirectToAction("ShowAll");
            }
            return View(raceTeam);
        }
        [Authorize(Roles = "admin, dispatcher")]
        // GET: RaceTeams/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RaceTeam raceTeam = repository.GetByID(id);
            if (raceTeam == null)
            {
                return HttpNotFound();
            }
            return View(raceTeam);
        }
        [Authorize(Roles = "admin, dispatcher")]
        // POST: RaceTeams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            repository.Delete(id);
            repository.Save();
            return RedirectToAction("ShowAll");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                repository.Dispose();
            }
            base.Dispose(disposing);
    }
    }
}

Airlines/Airlines.WebUI/Controllers/RacesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Airlines.Data.Entities;
using Airlines.Data.OtherActions;
using Airlines.Data.Repository;
using PagedList;

namespace Airlines.WebUI.Controllers
{
    public class RacesController : Controller
    {

        private IAirlineRepository<Race> repository;

        public RacesController()
        {

        }
        public RacesController(IAirlineRepository<Race> repo)
        {
            repository = repo;
        }
        [AllowAnonymous]
        public ViewResult Index(string sortOrder, int? currentFilter, int? number, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = sortOrder == "name" ? "name_desc" : "name";
            ViewBag.IDSortParm = String.IsNullOrEmpty(sortOrder) ? "ID_desc" : "";
            var races = repository.GetList();
            if (number != null)
            {
                page = 1;
            }
            else
            {
                number = currentFilter;
            }
            ViewBag.CurrentFilter = number;
            if (number != null)
            {
                races = races.Where(r => r.ID == number);
            }

            switch (sortOrder)
            {
                case "name":
                    races = races.OrderBy(s => s.Name);
                    break;
                case "ID_desc":
                    races = races.OrderByDescending(s => s.ID);
                    break;
                case "name_desc":
                    races = races.OrderByDescending(s => s.Name);
                    break;
                default:
                    races = races.OrderBy(s => s.ID);
                    break;
            }

            int pageSize = 7;
            int pageNumber = (page ?? 1);


            return View(races.ToPagedList(pageNumber, pageSize));
            //return View(races);
        }
        [AllowAnonymous]
        [HttpPost]
        public ActionResult Filter(string newDeparture, string newDestination, DateTime? newDate, int? page)
        {
            var races = repository.GetList();
            if (newDate == null || newDeparture == null || newDestination ==null)
            {
                    ModelState.AddModelError("", "Please make sure that all the parameters were used.");
            }            
            if (ModelState.IsValid)
            {
                races = races
                .Where(s => s.Departure == newDeparture)
                .Where(s => s.Destinaton == newDestination)
                .Where(s => s.Date == newDate);
                ViewBag.Date = newDate;
                ViewBag.Departure = newDeparture;
                ViewBag.Destination = newDestination;
            }

            int pageSize = 7;
            int pageNumber = (page ?? 1);


            return View("Index",races.ToPagedList(pageNumber, pageSize));
        }
        [Authorize(Roles ="admin")]
        // GET: Races/Create
        public ActionResult Create()
        {
            ViewBag.RaceTeamID = new SelectList(Methods.PopulateRaceTeamDropDownList(), "ID", "ID");
            return View();
        }

        [Authorize(Roles = "admin")]// POST: Races/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Departure,Destinaton,Date,IsDeparted,RaceTeamID")] Race race)
        {
            if (ModelState.IsValid)
            {
                repository.Create(race);
                repository.Save();
                return RedirectToAction("Index","Admin","");
            }

            ViewBag.RaceTeamID = new SelectList(Methods.PopulateRaceTeamDropDownList(), "ID", "ID", race.RaceTeamID);
            return View(race);
        }

        // GET: Races/Edit/5
        [Authorize(Roles = "admin, dispatcher")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Race race = repository.GetByID(id);
            if (race == null)
            {
                return HttpNotFound();
            }
            ViewBag.RaceTeamID = new SelectList(Methods.PopulateRaceTeamDropDownList(), "ID", "ID", race.RaceTeamID);
            return View(race);
        }

        // POST: Races/Edit/5
        [Authorize(Roles ="admin, dispatcher")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Departure,Destinaton,Date,IsDeparted,RaceTeamID")] Race race)
        {
            if (ModelState.IsValid)
            {
                repository.Update(race);
                repository.Save();

                if (User.IsInRole("admin"))
                {
                    return RedirectToAction("Index", "Admin", "");
                }
                else
                {
                    return RedirectToAction("Index", "Dispatcher", "");
                }
            }
            ViewBag.RaceTeamID = new SelectList(Methods.PopulateRaceTeamDropDownList(), "ID", "ID", race.RaceTeamID);
            return View(race);
        }
        [Authorize(Roles = "admin")]
        // GET: Races/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Race race = repository.GetByID(id);
            if (race == null)
            {
                return HttpNotFound();
            }
            return View(race);
        }
        [Authorize(Roles = "admin")]
        // POST: Races/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            repository.Delete(id);
            repository.Save();
            return RedirectToAction("Index", "Admin", "");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                repository.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Airlines/Airlines.WebUI/Views/Dispatcher/Index.cshtml
@model Airlines.WebUI.Models.AdminViewModel
<div id="modDialog" class="modal fade">
    <div id="dialogContent" class="modal-dialog"></div>
</div>
<div class="table-wrap">
    <table class="table">
        <tr>
            <th>
                Race Team
            </th>
            <th>
                Name
            </th>
            <th>
                Departure
            </th>
            <th>
                Destinaton
            </th>
            <th>
                Date
            </th>
            <th>
                Race Status
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model.Races)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.RaceTeam.ID) <br />
                    @if (item.RaceTeam != null)
                    {
                        @Html.ActionLink("Check roster", "Show", "RaceTeams", new { id = item.RaceTeam.ID }, new { @class = "compItem text-secondary my-link" })
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Departure)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Destinaton)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                @if (item.IsDeparted == true)
                {
                    <td>
                        In flight
                    </td>
                }

                else
                {
                    <td>
                        Incoming race
                    </td>

                }
                <td>
                    @Html.ActionLink("Add/Replace with a new Team", "Create", "RaceTeams", new { id = item.ID }, new { @class = "text-secondary my-link" }) |
                    @Html.ActionLink("Edit Date/Status/Team", "Edit", "Races", new { id = item.ID }, new { @class = "text-secondary my-link" })|
                    @Html.ActionLink("Send query to admin", "Create", "Queries", new { id = item.ID }, new { @class = "text-secondary my-link" })
                </td>

            </tr>
        }

    </table>
    </div>
    @section Scripts {
        <script src="~/Scripts/ModalWindow.js"></script>
    }

Airlines/Airlines.WebUI/Views/Dispatcher/Queries.cshtml
@model IEnumerable<Airlines.Data.Entities.Query>

@{
    ViewBag.Title = "Queries";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Queries</h2>


<table class="table">
    <tr>
        <th>
           Race Team
        </th>
        <th>
           Race
        </th>
        <th>
           Status
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.RaceTeamID)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.RaceID) <span> (@item.Race.Name)</span>
    </td>

        @if (item.IsAccepted == null)
        {
            <td>
                Pending
            </td>
        }
        @if (item.IsAccepted == false)
        {
            <td>
                Declined
            </td>
        }
        @if (item.IsAccepted == true)
        {
            <td>
                Accepted
            </td>
        }

    <td></td>
</tr>
}

</table>